### ISSUE TITLE
Out of the box, the "sitemap" link brings a Page Not Found

### ISSUE THREAD

**Issue by Steve-A-Orr** [pdxlibrary/Library-DIY#3]
I do plan on assisting with some Pull Requests, but quickly wanted to know how your group is accomplishing the Sitemap functions on your Production site:
http://library.pdx.edu/diy/sitemap

Is that using Views or do you have another module?

**Comment by mflakus** [comment]
Hi Steven,

 

Sorry for the issue. The sitemap link is meant to point to the sitemap.php theme file. There are no other modules needed, but you might need to adjust the location of that sample link based on your installation location so it points directly to the sitemap template file. 

 

-Mike

**Comment by Steve-A-Orr** [comment]
Please bare with me--I don't see a file named "sitemap.php" in the repository; not even "sitemap.tpl.php" which is probably what you mean. Would you point me to where it is located or provide me the code and I'll include it in my (planned) pull request?

**Comment by mflakus** [comment]
Hi Steven,

 

The file is actually located at the application root:

https://github.com/pdxlibrary/Library-DIY/blob/master/sitemap.php

 

The links in the left section that point to the sitemap page are set by editing the content of those sections.

 

-Mike

**Comment by Steve-A-Orr** [comment]
I certainly wasn't looking for it outside of the usual customization areas, but I see the file now. Thank you for being patient and pointing it out.

So, since my installation is residing in the suggested sub-directory ("/diy/") I would expect that a link of "/diy/sitemap.php" would work--but it does not. Is it possible that there is a need to make a change to the **.htaccess** file, which isn't reflected in the current repository?

I ask these questions, but obviously I'll need to experiment myself too. Thanks for your assistance so far.

**Comment by mflakus** [comment]
I just confirmed the .htaccess in the latest commit of the repository is the same version we are currently using for our production instance. Our sitemap URL is: http://library.pdx.edu/diy/sitemap.

 

I’m not sure why a similar link is not working for you.

 

-Mike

**Comment by Steve-A-Orr** [comment]
I just came back from lunch and read your reply. So, my "Test" environment is CentOs and my "Dev" environment is Fedora. Since it is not working out-of-the-box on either of them, then maybe I'm missing an Apache module or something is not configured the same as yours (like a module) in the database. It is confusing that Drupal as-a-whole is working, though, and just not this page.

I'll stick with the troubleshooting effort and share any results. (Probably stand up other VMs and test.)

**Comment by Steve-A-Orr** [comment]
Just an update, my fresh install on Fedora can find the sitemap file as long as the extension is included. (e.g., /diy/sitemap.php) The fact that your website also delivers the page without the extension (/diy/sitemap) tells me that I am missing a drupal/apache configuration step or redirect setting.

**Comment by Steve-A-Orr** [comment]
Might you have something in the **httpd.conf** file concerning the "sitemap" or maybe something beyond the normal PHP configuration (something allowing a PHP file to be served without an extension)? Also, if you would tell me what host OS you use, I can spin up a VM and test the repository installation steps on it. (Just going through all the ways I can think of to tease out the solution.)

**Comment by Steve-A-Orr** [comment]
I think I have the missing configuration setting pinned down; after reading this post:
http://superuser.com/questions/337626/how-is-apache-mapping-files-without-extensions

It is likely you have the Apache Option *MultiViews* configured, something like this:
```
Options Indexes FollowSymLinks MultiViews
```

Would you confirm whether you have this option configured in your **httpd.conf** file?

**Comment by cgeib** [comment]
That is correct. The MultiViews option is enabled in our web server.
