### ISSUE TITLE
Update of Fusion Theme to 7.x-2.2

### ISSUE THREAD

**Issue by Steve-A-Orr** [pdxlibrary/Library-DIY#5]
I was about to create and submit another pull request (containing all module updates from the last year) to you, but wanted to ask about the Fusion Theme which you have utilized. (Installed: **7.x-2.0-beta2**  vs.  Recommended: **7.x-2.2**)

When my library first started using your code-base, I attempted to update this theme to the latest version and it _broke everything_. So, I rolled it back without troubleshooting in order to get it up and running. I have avoided the issue ever since...but it shouldn't be this way, so I wanted to ask if your developers have attempted an upgrade and, if so, **did you find a solution for the problem**?

I can submit a pull request without updating the theme, just like last time, but wanted to check first.

**Comment by cgeib** [comment]
Steve, we haven't addressed the theme update yet. Go ahead and submit your pull request without the theme update.

**Comment by Steve-A-Orr** [comment]
Mr. Geib, I have been updating our DIY installation without contributing back. I'd thought a _Pull Request_ could be sent soon, though, with current updates. I'm going to open another issue soon on a different, but related topic. Look for that too.
